name: awesomeapp
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  http: ^0.13.3
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
    - family: Poppins Reguler
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 400
    - family: Poppins Extra Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 400
