name: awesomeapp
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  http: ^0.13.3
  string_validator: ^0.3.0
  google_fonts: ^2.1.0
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/evermos_cover.jpg
